### ISSUE TITLE
Helm chart crashes when ai.openai.api_key is not defined in values.yaml

### ISSUE THREAD

**Issue by danc094codetogether** [CodeTogether-Inc/CodeTogether-Deployment#115]
**Description:**

We have a critical issue in the Intel Helm chart when running:

`helm template intel ./charts/intel --values ./charts/intel/values.yaml`

It produces the following error:

`Error: template: codetogether-intel/templates/secrets.yaml:7:28: executing "codetogether-intel/templates/secrets.yaml" at <.Values.ai.openai.api_key>: nil pointer evaluating interface {}.api_key`

**Root Cause:**

The chart unconditionally references .Values.ai.openai.api_key, but in our values.yaml, we are using:

```
ai:
  mode: "bundled"  # Options: bundled | external
  provider: "ollama"  # No OpenAI dependency
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
      gpu: false
    limits:
      cpu: "4"
      memory: "8Gi"
      gpu: false
  image:
    repository: registry.digitalocean.com/codetogether-registry/ai-summarization
    tag: latest
```

There is no ai.openai block, leading to a nil pointer evaluation.

**Proposed Fix:**

Patch the Helm template to check if .Values.ai.openai is defined before accessing api_key.
