### ISSUE TITLE
Automatically configure Ollama integration when LLM is enabled

### ISSUE THREAD

**Issue by wgalanciak** [CodeTogether-Inc/CodeTogether-Deployment#126]
### Description

If as a part of the intel deployment, the ai service is enabled:
```
..
ai:
  enabled: true
..
```

We should pass required information to the codetogether-intel container to provide default plugin configuration. To do it, we need to set the following env variables:
```
- CT_HQ_OLLAMA_AI_API_KEY
- CT_HQ_OLLAMA_AI_URL
- CT_HQ_OLLAMA_AI_MODEL_NAME
```

**Comment by danc094codetogether** [comment]
### **To configure the AI integration, follow these steps for each mode:**

**Bundled mode:**

In the values.yaml, set:

```
ai:
  enabled: true
  mode: "bundled"
  image:
    repository: <bundled-ai-image>
    tag: <tag>
```
No extra resources are required. The deployment will automatically run the AI as a sidecar container within the same Pod.

**External mode:**

In the values.yaml, set:


```
ai:
  enabled: true
  mode: "external"
```
Create a ConfigMap and a Secret (external-config.yaml) in the namespace:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-config
  namespace: <namespace>
data:
  ai_provider: "<provider-name>"
  ai_url: "<external-ai-url>"

---

apiVersion: v1
kind: Secret
metadata:
  name: ai-external-secret
  namespace: <namespace>
type: Opaque
stringData:
  api-key: "<external-api-key>"
```
The deployment will use these resources to connect to the external AI service.

**Notes:**

- For bundled, everything is managed by the chart just set the mode and image.
- 
- For external, make sure the ConfigMap and Secret exist in the namespace before deploying or upgrading.
