### ISSUE TITLE
Fix invalid GPU resource value in values.yaml

### ISSUE THREAD

**Issue by wgalanciak** [CodeTogether-Inc/CodeTogether-Deployment#136]
## Description

During deployment of the intel Helm chart with ai.enabled: true, the installation fails due to an invalid value provided under resources.requests.gpu and resources.limits.gpu. The value false does not match the expected format for Kubernetes quantity strings.

**Error:**

`Deployment in version "v1" cannot be handled as a Deployment: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`

**Root Cause**
The field gpu: false was incorrectly defined. Kubernetes expects quantity-style values (e.g., "1"), not booleans.

**Fix**
Update the values.yaml file to either:

Remove the gpu fields entirely if GPU is not required.

Or set valid quantity strings for GPU if needed, e.g., gpu: "1".

**Example:**

```
ai:
  enabled: true
  mode: "bundled"
  image:
    repository: hub.edge.codetogether.com/releases/codetogether-llm
    tag: latest
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
      # gpu: "1"   # Uncomment and set only if GPU is needed
    limits:
      cpu: "4"
      memory: "4Gi"
      # gpu: "1"
```
**Next Steps**

- [ ]  Validate that the Helm chart does not expect a gpu key unless explicitly supported.
